#!/bin/bash

LOADBALANCE_DIR=/var/load-balance


prefix=/opt/vyatta
sysconfdir=${prefix}/etc

mkdir -p $LOADBALANCE_DIR
chmod 0755 $LOADBALANCE_DIR

rm -f /etc/init.d/vyatta-wanloadbalance 2>/dev/null
ln -s /opt/vyatta/sbin/vyatta-wanloadbalance.init /etc/init.d/vyatta-wanloadbalance 2>/dev/null

#because I'm lazy and don't want to have to create an extra pkg for the show cmd
mkdir -p /opt/vyatta/share/vyatta-op/templates/show/wan-load-balance/
mv /opt/vyatta/share/vyatta-cfg/templates/show/wan-load-balance/node.def /opt/vyatta/share/vyatta-op/templates/show/wan-load-balance/.


#nothing
