#! /bin/bash

declare progname=${0##*/}
declare action=$1; shift

conf=$1; shift


test -x $bb  || exit 0

start ()
{
    /opt/vyatta/sbin/wan_lb -f $conf -d -i /var/run/vyatta/wlb.pid
}

stop ()
{
    kill -s SIGTERM $( cat /var/run/vyatta/wlb.pid )
}

case "$action" in
  start)	start;;
  stop)		stop;;
  restart)	stop; sleep 1; start;;
  *)	echo "Usage: $progname {start|stop|restart}"
	exit 1
esac
